library(readr)
pokedex <- read_csv("Pokemon project/pokedex_(Update_05.20).csv")
View(pokedex)
gen1 = subset(pokedex, generation == 1)
gen2_8 = subset(pokedex, generation == 2 | generation == 3 | generation == 4 | generation == 5 | generation == 6 | generation == 7 | generation == 8)
mean(gen1$total_points)
mean(gen2_8$total_points)
var(gen1$total_points)
var(gen2_8$total_points)
t.test(gen1$total_points, gen2_8$total_points, alternative = "less")
gen8 = subset(pokedex, generation == 8)
mean(gen8$total_points)
var(gen8$total_points)
t.test(gen1$total_points, gen8$total_points, alternative = "less")
