library(readr)
pokedex <- read_csv("Pokemon project/pokedex_(Update_05.20).csv")
View(pokedex)
hist(pokedex$attack, main = "Distribution of Attack", xlab = "Attack", ylab = "Frequency")
mean(pokedex$attack)
median(pokedex$attack)
var(pokedex$attack)
sd(pokedex$attack)
hist(pokedex$defense, main = "Distribution of Defense", xlab = "Defense", ylab = "Frequency")
mean(pokedex$defense)
median(pokedex$defense)
var(pokedex$defense)
sd(pokedex$defense)
hist(pokedex$sp_attack, main = "Distribution of Special Attack", xlab = "Special Attack", ylab = "Frequency")
mean(pokedex$sp_attack)
median(pokedex$sp_attack)
var(pokedex$sp_attack)
sd(pokedex$sp_attack)
hist(pokedex$sp_defense, main = "Distribution of Special Defense", xlab = "Special Defense", ylab = "Frequency")
mean(pokedex$sp_defense)
median(pokedex$sp_defense)
var(pokedex$sp_defense)
sd(pokedex$sp_defense)
hist(pokedex$speed, main = "Distribution of Speed", xlab = "Speed", ylab = "Frequency")
mean(pokedex$speed)
median(pokedex$speed)
var(pokedex$speed)
sd(pokedex$speed)
hist(pokedex$hp, main = "Distribution of HP", xlab = "HP", ylab = "Frequency")
mean(pokedex$hp)
median(pokedex$hp)
var(pokedex$hp)
sd(pokedex$hp)
